apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: hook-test
version: 0.1.0
sources:
- https://github.com/jainishshah17/Chart-post-install-hook
maintainers:
- name: jainishshah17
  email: jainishshah@yahoo.com
icon: https://github.com/jainishshah17/jainishshah.com/blob/master/app/public/images/logo.jpg
home: http://jainishshah.com/